### ISSUE TITLE
vendetta icon is white with material you icons

### ISSUE THREAD

**Issue by auriafoxgirl** [vendetta-mod/VendettaManager#57] opened 2024-01-07 21:35 UTC
The vendetta icon is white instead of material you like normal discord icon when change icon in manager is enabled.
![Screenshot_20240107_222353_One UI Home](https://github.com/vendetta-mod/VendettaManager/assets/53555592/13e571bf-663e-4d11-83c7-5c560cee6899)

After looking a bit through apk files of both discord and vendetta it seems like the vendetta is changing background of wrong image `ic_logo_foreground.png`
discord (background is transparent):
![Screenshot_20240107_222635_MiXplorer](https://github.com/vendetta-mod/VendettaManager/assets/53555592/eab3258b-bf9f-4f41-a3d3-f8b84088c6c7)
vendetta (background have color):
![Screenshot_20240107_222812_MiXplorer](https://github.com/vendetta-mod/VendettaManager/assets/53555592/4dc9b260-da69-4c0c-9b22-79e5fd653734)

Vendetta manager might be changing background in wrong file with makes thing that controls rendering of material you icons think that the background is part of foreground icon and colors it resulting in background being colored with icon with white.
Vendetta manager should change background color of all those files:
![Screenshot_20240107_223354_MiXplorer](https://github.com/vendetta-mod/VendettaManager/assets/53555592/2e66bb10-5744-4981-8c3a-1665b7defc79)
instead of changing background of file that was supposed to have transparent background.

**Comment by Cynosphere** [comment] 2024-01-07 21:41
Duplicate of #5 

(disable icon replacement if it annoys you that much)

**Closed** 2024-01-07 21:57 UTC
Labels: duplicate
