### ISSUE TITLE
Request: Custom Icon

### ISSUE THREAD

**Issue by VioletStorm** [vendetta-mod/VendettaManager#15] opened 2023-06-13 08:12 UTC
Add the ability to set any png as the discord app icon, and/or have a slider to simply recolour the official discord icon

Please don't reject this because "icon packs" or "app launchers" as those CAN NOT change the icon globally, it's an android limitation, the original icon will always be displayed system wide with acceptions being limited to only where a launcher has direct influence

**Comment by wingio** [comment] 2023-06-14 14:53
Im gonna close this as a duplicate of #7

**Closed** 2023-06-14 14:53 UTC
Labels: duplicate, feature request
