### ISSUE TITLE
Package Installer keeps stopping

### ISSUE THREAD

**Issue by theoparis** [vendetta-mod/VendettaManager#60] opened 2024-01-11 22:31 UTC
I downloaded the [latest Manager.apk](https://github.com/vendetta-mod/VendettaManager/releases/download/1100/Manager.apk) and clicked it and it prompted with the normal android package installer popup. However clicking install doesn't do anything - it just closes the popup without actually installing anything. 
I double checked with another apk (https://github.com/ImranR98/Obtainium) and it works fine.
Sometimes after trying to install manager.apk several times it just says "Package Installer keeps stopping".

I'm using android 14 on a pixel 7a if that helps.

**Comment by Cynosphere** [comment] 2024-01-11 22:33
Duplicate of #54
(common Pixel issue, use Google Files or install through adb/pm)

**Closed** 2024-01-12 19:14 UTC
